x-common-environment: &common-environment
  MYSQL_ROOT_PASSWORD: dev
  MYSQL_DATABASE: dev
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev
  MYSQL_PORT: 3306

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: docker/Dockerfile
    image: anitunes_dev:1.5
    command: [npm, run, debug]
    init: true
    volumes:
      - ./next-app:/app
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    environment:
      MYSQL_HOST: db
      <<: *common-environment
  db:
    container_name: db
    image: mysql:8.0-debian
    ports:
      - 3306:3306
    environment:
      <<: *common-environment
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
